version: '3.8'

services:
  forum-nodejs-api:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: forum-nodejs-api

